### ISSUE TITLE
IsAnInteractiveSession is deprecated

### ISSUE THREAD

**Issue by TobiX** [kardianos/minwinsvc#4]
Hi!

Just a minor nit: [`IsAnInteractiveSession`](https://pkg.go.dev/golang.org/x/sys/windows/svc@v0.0.0-20210629170331-7dc0b73dc9fb#IsAnInteractiveSession) is deprecated and the authors suggest switching to `IsWindowsService` instead, which AFAICS has stricter semantics, so this would probably avoid things like #1 or #2 in the future :smile:

**Comment by luuquocviet79** [comment]
https://github.com/kardianos/minwinsvc/issues/4#issue-933373544
