### ISSUE TITLE
Causes issues on WinPE

### ISSUE THREAD

**Issue by xaduha** [kardianos/minwinsvc#5]
````
package main

import (
	"log"
	"time"

	_ "github.com/kardianos/minwinsvc"
)

func main() {
	log.Println("one")
	time.Sleep(time.Second)
	log.Println("two")
}
````

on Win10-based WinPE this snippet doesn't get to "two". My fault for including minwinsvc where it shouldn't have been, but this doesn't even return panic message, just silently dies, couldn't figure out what was going on in my actual program.

**Comment by kardianos** [comment]
It can't panic because windows kills it.
